use_frameworks!

platform :ios, '9.0'
#install! 'cocoapods',
#disable_input_output_paths: true,
#generate_multiple_pod_projects: true
use_modular_headers!
target 'MyLibrary_Example' do
  pod 'MyLibrary', :path => '../'

  target 'MyLibrary_Tests' do
    inherit! :search_paths

    
  end
end
